# Generated by Django 5.1.2 on 2024-11-13 14:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import thesecretgarden.accounts.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30, validators=[thesecretgarden.accounts.validators.NameValidator(field_name='first name')], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[thesecretgarden.accounts.validators.NameValidator(field_name='last name')], verbose_name='Last Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('preferred_flower_type', models.CharField(blank=True, choices=[('non-floral', 'Non Floral Plants'), ('floral', 'Floral Plants'), ('cactus', 'Cactuses')], max_length=10, null=True, verbose_name='Preferred Flower Type')),
            ],
            options={
                'verbose_name': 'Profile',
                'ordering': ['user'],
            },
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), thesecretgarden.accounts.validators.UsernameValidator()], verbose_name='Username'),
        ),
    ]
