# Generated by Django 5.1.2 on 2024-11-21 12:23

import django.core.validators
import thesecretgarden.flowers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter plant name (up to 3 words).', max_length=50, unique=True, validators=[thesecretgarden.flowers.validators.PlantNameValidator()], verbose_name='Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('non-floral', 'Non Floral Plants'), ('floral', 'Floral Plants'), ('cactus', 'Cactus')], default='floral', help_text='Provide plant type.', max_length=10, verbose_name='Type')),
                ('description', models.TextField(help_text='Provide a description for the plant product.', validators=[thesecretgarden.flowers.validators.PlantDescriptionValidator(), django.core.validators.MinLengthValidator(10, message='Description should be at least 10 characters.'), django.core.validators.MaxLengthValidator(300, message='Description should not exceed 1000 characters.')], verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Provide plant price.', max_digits=7, validators=[thesecretgarden.flowers.validators.PlantPriceValidator()], verbose_name='Price')),
                ('stock', models.PositiveIntegerField(help_text='Provide stock amount.', verbose_name='Stock')),
                ('photo', models.ImageField(upload_to='images/flowers', validators=[thesecretgarden.flowers.validators.FileSizeValidator(5)])),
            ],
            options={
                'verbose_name': 'Plant',
                'ordering': ['name'],
            },
        ),
    ]
