# Generated by Django 5.1.2 on 2024-11-17 14:57

import thesecretgarden.flowers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='Enter plant name (up to 3 words).', max_length=50, unique=True, validators=[thesecretgarden.flowers.validators.PlantNameValidator()], verbose_name='Type'),
        ),
    ]
