# Generated by Django 5.1.2 on 2024-11-21 18:07

import thesecretgarden.flowers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Provide plant price.', max_digits=5, validators=[thesecretgarden.flowers.validators.PlantPriceValidator()], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='stock',
            field=models.PositiveIntegerField(help_text='Provide stock amount.', validators=[thesecretgarden.flowers.validators.PlantStockValidator()], verbose_name='Stock'),
        ),
    ]
