# Generated by Django 5.1.2 on 2024-12-05 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(help_text='Provide a description for the plant product.', validators=[django.core.validators.MinLengthValidator(10, message='Description should be at least 10 characters.'), django.core.validators.MaxLengthValidator(300, message='Description should not exceed 300 characters.')], verbose_name='Description'),
        ),
    ]
