# Generated by Django 5.1.2 on 2024-11-18 09:03

import thesecretgarden.flowers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_alter_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Provide plant price.', max_digits=7, validators=[thesecretgarden.flowers.validators.PlantPriceValidator()], verbose_name='Price'),
        ),
    ]
