# Generated by Django 5.1.2 on 2024-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_alter_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('non-floral', 'Non Floral Plants'), ('floral', 'Floral Plants'), ('cactus', 'Cactus')], default='floral', help_text='Provide plant type.', max_length=10, verbose_name='Type'),
        ),
    ]
