# Generated by Django 5.1.2 on 2024-11-29 17:05

import cloudinary.models
import django.core.validators
import thesecretgarden.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, help_text='Provide product price.', max_digits=5, validators=[thesecretgarden.common.validators.ProductPriceValidator()], verbose_name='Price')),
                ('stock', models.PositiveIntegerField(help_text='Provide stock amount.', validators=[thesecretgarden.common.validators.ProductStockValidator()], verbose_name='Stock')),
                ('photo', cloudinary.models.CloudinaryField(help_text='Upload an image for the product.', max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(help_text='Enter product name (up to 3 words).', max_length=50, unique=True, validators=[thesecretgarden.common.validators.ProductNameValidator()], verbose_name='Product Name')),
                ('short_name', models.CharField(help_text='Enter the product short name.', max_length=50, verbose_name='Short Name')),
                ('short_description', models.CharField(help_text='Enter short product description.', max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Short Description')),
                ('type', models.CharField(choices=[('red wine', 'Red Wine'), ('chocolate', 'Chocolate'), ('candle', 'Candle')], default='red wine', help_text='Provide gift type.', max_length=9, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Gift',
            },
        ),
    ]
