# Generated by Django 5.1.2 on 2024-11-18 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='brand_name',
            field=models.CharField(help_text='Enter the brand name.', max_length=50, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='short_name',
            field=models.CharField(help_text='Enter the product short name.', max_length=50, verbose_name='Short Name'),
        ),
    ]
