# Generated by Django 5.1.2 on 2024-11-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_alter_gift_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='type',
            field=models.CharField(choices=[('red wine', 'Red Wine'), ('chocolate', 'Chocolate'), ('candle', 'Candle')], help_text='Provide gift type.', max_length=9, verbose_name='Type'),
        ),
    ]
