# Generated by Django 5.1.2 on 2024-12-01 15:26

import django.db.models.deletion
import thesecretgarden.orders.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Completed', 'completed'), ('Canceled', 'canceled')], default='pending', help_text='The current status of the order.', max_length=10, verbose_name='Order Status')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='The total price for the order.', max_digits=9, verbose_name='Total Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who placed the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Order Owner')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(help_text='Provide order quantity.', validators=[thesecretgarden.orders.validators.MaxQuantityValidator(max_quantity=30)], verbose_name='Product Quantity')),
                ('current_stock', models.PositiveIntegerField(editable=False, help_text='Product stock at the time of order.')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit at the time of order.', max_digits=5, verbose_name='Price')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='The total price for this item.', max_digits=7, verbose_name='Total Price')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Order')),
            ],
        ),
    ]
