# Generated by Django 5.1.2 on 2024-12-01 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', help_text='The current status of the order.', max_length=10, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='content_type',
            field=models.ForeignKey(help_text='The type of the product (e.g., plant, gift).', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='object_id',
            field=models.PositiveIntegerField(help_text='The ID of the product being referenced.'),
        ),
    ]
