# Generated by Django 5.1.2 on 2024-12-05 12:08

import django.core.validators
import thesecretgarden.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter your name.', max_length=100, validators=[thesecretgarden.common.validators.ContactNameValidator(), django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('email', models.EmailField(help_text='Please provide an email.', max_length=254, verbose_name='Email')),
                ('message', models.TextField(help_text='Please enter your message.', validators=[thesecretgarden.common.validators.ContactMessageValidator()], verbose_name='Your message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
